config/routes.rb
Dismassales::Application.routes.draw do
  resources :orders

  resources :categories

  resources :items

  match 'store/' => 'storefront#index', :as => :storefront
  match 'store/item/:id' => 'itemdetail#index', :as => :itemdetail
  match 'store/item/itemimage/:id' => 'itemdetail#image', :as => :itemimage
  match 'item/saveimage' => 'items#add_image', :as => :saveitemimage
  match 'store/shoppingcart' => 'shopping_cart#index', :as => :shoppingcart
  match 'store/shoppingcart/addtocart' => 'shopping_cart#addtocart', :as => :addtocart
  match 'store/shoppingcart/updatecart' => 'shopping_cart#updatecart', :as => :updatecart
  match 'store/shoppingcart/removeitem/:id' => 'shopping_cart#removeitem', :as => :removeitem
  match 'searchorders/' => 'orders#index', :as => :order_search
  match 'orderdetail/:id' => 'orders#detail', :as => :order_detail
  match 'shiporder/:id' => 'orders#shiporder', :as => :shiporder

  get "paypal_express/checkout"
  get "paypal_express/review"
  get "paypal_express/purchase"

  root :to => 'storefront#index'

end

app/models/order.rb
# implementation of the design item 7 -­ Create New Address and 9 -­ Order completed

class Order < ActiveRecord::Base
	attr_accessible :address1, :address2, :city, :name, :state, :surname, :zip, :date_created, :shipping_date

	has_many :order_items, :dependent => :destroy, :autosave => :true, :order => 'id'

	validates :address1, :city, :name, :state, :surname, :zip, :presence => true

 	def self.createFromCart(params, cart)
 		order = Order.new(params)
 		order.date_created = Date.today
 		order.save
 		#the .save method dont throws exeptions, just save errors. Just proceed if no error happened
 		if order.errors.size < 1
 			cart.cart_items.each do |cart_item|
	 			order_item = OrderItem.new
	 			order_item.item = cart_item.item;
	 			order_item.order = order;
	 			order_item.quantity = cart_item.quantity;
	 			order_item.save
	 		end
	 		#reload all the values from the database, list the new order_item
	 		order.reload
 		end
 		order
	end

	def self.createFromCartAndPaypal(params, cart, gateway_response)
 		order = Order.new
 		order.address1 = gateway_response.params['street1']
 		order.address2 = gateway_response.params['street2']
 		order.city = gateway_response.params['city_name']
 		order.zip = gateway_response.params['postal_code']
 		order.state = gateway_response.params['state_or_province']
 		order.name = gateway_response.params['first_name']
 		order.surname = gateway_response.params['last_name']
 		order.date_created = Date.today
 		order.save
 		#the .save method dont throws exeptions, just save errors. Just proceed if no error happened
 		if order.errors.size < 1
 			cart.cart_items.each do |cart_item|
	 			order_item = OrderItem.new
	 			order_item.item = cart_item.item;
	 			order_item.order = order;
	 			order_item.quantity = cart_item.quantity;
	 			order_item.save
	 		end
	 		#reload all the values from the database, list the new order_item
	 		order.reload
 		end
 		order
	end

	def self.findByFilter(params)
		orders = Order.where("")

		if params['number'] != nil && params['number'] != ''
			orders = orders.where("id = ?", params['number'])
		end

		if params['created1'] != nil && params['created1'] != ''
			orders = orders.where("date_created >= ?", Date.parse(params['created1'])) 
		end

		if params['created2'] != nil && params['created2'] != ''
			orders = orders.where("date_created <= ?", Date.parse(params['created2'])) 
		end

		if params['open'] != nil && params['open'] != '' && params['shipped'] != nil && params['shipped'] != ''

			if params['open'] == nil || params['open'] == ''
				orders = orders.where("shipping_date is not null") 
			end

			if params['shipped'] == nil || params['shipped'] == ''
				orders = orders.where("shipping_date is null") 
			end

		end

		if params['shipped1'] != nil && params['shipped1'] != ''
			orders = orders.where("shipping_date >= ?", Date.parse(params['shipped1'])) 
		end

		if params['shipped2'] != nil && params['shipped2'] != ''
			orders = orders.where("shipping_date <= ?", Date.parse(params['shipped2'])) 
		end

		if params['name'] != nil && params['name'] != ''
			orders = orders.where("name like ?", params['name'])
		end

		orders
	end
end

app/controllers/orders_controller.rb
# implementation of the design item 7 -­ Create New Address and 9 -­ Order completed and 12 -­ Track orders ­ Search and 13 -­ Track Orders ­ Detail:

# there is some unused code right now, but it will be used in the orders hstory later

class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.findByFilter(params)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    @howmuchitems = Cart.howMuchItems(request.session_options[:id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    cart = Cart.createOrFind(request.session_options[:id])
    @order = Order.createFromCart(params[:order], cart)

    @howmuchitems = Cart.howMuchItems(request.session_options[:id])

    if @order.errors.size < 1
      reset_session
    end

    respond_to do |format|
      if @order.errors.size < 1
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def detail
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @order }
    end
  end

  def shiporder
    #puts shipping date in the order
    @order = Order.find(params[:id])
    @order.shipping_date = Date.today
    @order.save

    redirect_to order_detail_path(@order)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%-# Implementation of the design items 7 -­ Create New Address %>

<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><span class="requiredfield">*</span><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :surname %><span class="requiredfield">*</span><br />
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :address1 %><span class="requiredfield">*</span><br />
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br />
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><span class="requiredfield">*</span><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><span class="requiredfield">*</span><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><span class="requiredfield">*</span><br />
    <%= f.number_field :zip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/detail.html.erb
<%-# Implementation of the design item 13 -­ Track Orders ­ Detail %>

<style>
    #itemstable {
        width: 900px;
        border: 1px solid #999;
        padding: 0px;
        margin: 0px;
        border-collapse: collapse;
    }

    #itemstable th {
        border: 1px solid #999;
    }

    #itemstable td {
        border: 1px solid #999;
        
    }

    #bottomtable {
      width: 900px;
    }

    #checkoutbuttonenclose {
      width: 450px;
      float: right;
      text-align: right;
    }
</style>

<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @order.name %>
</p>

<p>
  <b>Surname:</b>
  <%= @order.surname %>
</p>

<p>
  <b>Address1:</b>
  <%= @order.address1 %>
</p>

<p>
  <b>Address2:</b>
  <%= @order.address2 %>
</p>

<p>
  <b>City:</b>
  <%= @order.city %>
</p>

<p>
  <b>State:</b>
  <%= @order.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @order.zip %>
</p>

<p>
  <b>Date Created:</b>
  <%= @order.date_created %>
</p>

<p>
  <b>Shipping Date:</b>
  <%= @order.shipping_date %>
</p>

<%-# grid showing all the items of the order %>
<table id="itemstable">
  <tr>
    <th>Code</th>
    <th>Name</th>
    <th>Quantity</th>
    <th>Price</th>
    <th>Total Value</th>
    
  </tr>

<% @order.order_items.each do |orderitem| %>
  <tr>
    <td><%= orderitem.item.code %></td>
    <td><%= orderitem.item.title %></td>
    <td style="text-align: center"><%= orderitem.quantity %></td>
    <td style="text-align: center"><%= number_to_currency(orderitem.item.price) %></td>
    <td style="text-align: center"><%= number_to_currency(orderitem.item.price * orderitem.quantity) %></td>
  </tr>
<% end %>
</table>

<% if @order.shipping_date == nil %>
  <%-# This button calls an action that adds shipping date to the order %>
  <button type="button" onclick="window.location.href = '/shiporder/<%= @order.id %>'; return false;">Mark as shipped</button>
<% end %>

</br>

<%= link_to 'Back', orders_path %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<%-# Implementation of the design item 12 -­ Track orders ­ Search %>

<h1>Listing orders</h1>

<%= form_tag(order_search_path, :method => "post") do %>
    <div class="field">
        Number: <br />
        <%= text_field_tag('number') %>
    </div>
    <div class="field">
        Created between: <br />
        <%= text_field_tag 'created1', '', :onchange => "validateDate(this)"  %> and <%= text_field_tag 'created2', '', :onchange => "validateDate(this)" %>
    </div>
    <div class="field">
        Order Status: <br />
        <%= check_box_tag 'open', 'open', true %> Open <%= check_box_tag 'shipped', 'shipped', true %> Shipped
    </div>
    <div class="field">
        Shipped between: <br />
        <%= text_field_tag 'shipped1', '', :onchange => "validateDate(this)"  %> and <%= text_field_tag 'shipped2', '', :onchange => "validateDate(this)" %>
    </div>
    <div class="field">
        User Name: <br />
        <%= text_field_tag('name') %>
    </div>
    <%= submit_tag "Search" %>
<% end %>

<table>
  <tr>
    <th>Number</th>
    <th>Name</th>
    <th>Surname</th>
    <th>Address1</th>
    <th>Address2</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>Date Created</th>
    <th>Shipping Date</th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.id %></td>
    <td><%= order.name %></td>
    <td><%= order.surname %></td>
    <td><%= order.address1 %></td>
    <td><%= order.address2 %></td>
    <td><%= order.city %></td>
    <td><%= order.state %></td>
    <td><%= order.zip %></td>
    <td><%= order.date_created %></td>
    <td><%= order.shipping_date %></td>
    <td><%= link_to 'Show', order_detail_path(order) %></td>
  </tr>
<% end %>
</table>

<br />

app/views/orders/new.html.erb
<%-# Implementation of the design items 7 -­ Create New Address %>

<style>
    #wrap {
    	width: 1000px;
    }

    #content {
    	width: 936px;
        
        float: right;
        background-color:#fff;
        padding: 20px;
        margin: 10px;
        border-width:2px;
        border-style:solid;
        border-color: #999;
    }
</style>

<div id="wrap">
	<%= render :partial => "/layouts/header" %>

	<div id="content">

		<h1>Create order</h1>

		<%= render 'form' %>

		<%= link_to 'Back', shoppingcart_path %>
	</div>
</div>

app/views/orders/show.html.erb
<%-# Implementation of the design items 9 -­ Order completed %>

<style>
    #wrap {
      width: 1000px;
    }

    #content {
      width: 936px;
        
        float: right;
        background-color:#fff;
        padding: 20px;
        margin: 10px;
        border-width:2px;
        border-style:solid;
        border-color: #999;
    }
</style>

<div id="wrap">
  <%= render :partial => "/layouts/header" %>

  <div id="content">

    <p id="notice"><%= notice %></p>

    <p>
      Your order number is:
      <b><%= @order.id %></b>
    </p>

    <p>
      Details of your order were sent by Paypal to your email address.
    </p>

  </div>
</div>