config/routes.rb
Dismassales::Application.routes.draw do
  resources :orders

  resources :categories

  resources :items

  match 'store/' => 'storefront#index', :as => :storefront
  match 'store/item/:id' => 'itemdetail#index', :as => :itemdetail
  match 'store/item/itemimage/:id' => 'itemdetail#image', :as => :itemimage
  match 'item/saveimage' => 'items#add_image', :as => :saveitemimage
  match 'store/shoppingcart' => 'shopping_cart#index', :as => :shoppingcart
  match 'store/shoppingcart/addtocart' => 'shopping_cart#addtocart', :as => :addtocart
  match 'store/shoppingcart/updatecart' => 'shopping_cart#updatecart', :as => :updatecart
  match 'store/shoppingcart/removeitem/:id' => 'shopping_cart#removeitem', :as => :removeitem
  match 'searchorders/' => 'orders#index', :as => :order_search
  match 'orderdetail/:id' => 'orders#detail', :as => :order_detail
  match 'shiporder/:id' => 'orders#shiporder', :as => :shiporder

  get "paypal_express/checkout"
  get "paypal_express/review"
  get "paypal_express/purchase"

  root :to => 'storefront#index'

end

app/controllers/shopping_cart_controller.rb
# implementation of the design item 4 -­ Shopping Cart

class ShoppingCartController < ApplicationController

	def index
		@cart = Cart.createOrFind(request.session_options[:id])
		@howmuchitems = Cart.howMuchItems(request.session_options[:id])
		@totalvalue = @cart.calculateTotalValue

		respond_to do |format|
	      format.html
	    end
	end

	def addtocart
		cart = Cart.createOrFind(request.session_options[:id])

		item = Item.find(params[:item_id])

    	CartItem.createCartItem(item, cart, params[:quantity].to_i);

		respond_to do |format|
	    	format.html { redirect_to shoppingcart_url }
	    end
	end

	def updatecart
		@cart = Cart.createOrFind(request.session_options[:id])

		@howmuchitems = Cart.howMuchItems(request.session_options[:id])

		items_to_be_updated = Hash.new

	    #parse parameters
	    params.each do |key, value|
	      if key.start_with?('quantity_')
	        items_to_be_updated[key[9..key.length-1]] = value;
	      end
	      
	    end;
	    
	    @cart = Cart.UpdateQuantities(@cart, items_to_be_updated);

	    @totalvalue = @cart.calculateTotalValue

	    respond_to do |format|
	      format.html { render :action => "index" }
	      format.json { render json: @cart }
	    end
	end

	def removeitem
		cart_item = CartItem.find(params[:id])
		cart_item.destroy

		@cart = Cart.createOrFind(request.session_options[:id])

		@totalvalue = @cart.calculateTotalValue

		@howmuchitems = Cart.howMuchItems(request.session_options[:id])
		
		respond_to do |format|
	      format.html { render :action => "index" }
	    end
	end
end

app/helpers/shopping_cart_helper.rb
module ShoppingCartHelper
end

app/views/shopping_cart/index.html.erb
<%-# Implementation of the design item 4 -­ Shopping Cart %>
<%-#Shopping cart view %>

<style>
    #wrap {
    	width: 1000px;
    }

    #content {
    	width: 936px;
        float: right;
        background-color:#fff;
        padding: 20px;
        margin: 10px;
        border-width:2px;
        border-style:solid;
        border-color: #999;
    }

    #shoppingcarttable {
        width: 900px;
        border: 1px solid #999;
        padding: 0px;
        margin: 0px;
        border-collapse: collapse;
    }

    #shoppingcarttable th {
        border: 1px solid #999;
    }

    #shoppingcarttable td {
        border: 1px solid #999;
        
    }

    #bottomtable {
      width: 900px;
    }

    #checkoutbuttonenclose {
      width: 450px;
      float: right;
      text-align: right;
    }
</style>

<div id="wrap">
	<%= render :partial => "/layouts/header" %>

	<div id="content">
		<%= form_tag(updatecart_path, :method => "post") do %>

      <%-# If some error occurs in updating the cart shows an div with the errors -%>
      <% if @cart.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@cart.errors.count, "error") %> prohibited the shopping cart from being updated:</h2>

          <ul>
          <% @cart.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <p id="notice"><%= notice %></p>

      <table id="shoppingcarttable">
        <tr>
          <th>Name</th>
          <th>Quantity</th>
          <th>Price</th>
          <th>Total Value</th>
          <th>Remove</th>
        </tr>

      <% @cart.cart_items.each do |cartitem| %>
        <tr>
          <td><%= cartitem.item.title %></td>
          <td><%= text_field_tag('quantity_' + cartitem.id.to_s, cartitem.quantity) %></td>
          <td style="text-align: center"><%= number_to_currency(cartitem.item.price) %></td>
          <td style="text-align: center"><%= number_to_currency(cartitem.item.price * cartitem.quantity) %></td>
          <td style="text-align: center"><%= link_to image_tag('remove.png'), removeitem_path(cartitem) %></td>
        </tr>
      <% end %>
      </table>
    <%-# Only shows the Update Quantities button if the user have items in the shopping cart -%>
    <div id="bottomtable">
      <% if @cart.cart_items.any? %>
          <%= submit_tag "Update Quantities" %>
          <div id="checkoutbuttonenclose">
            <b>Total value: <%= number_to_currency(@totalvalue) %></b><br/>
            
            <%= link_to image_tag("https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif"), :controller => 'paypal_express', :action => 'checkout' %>
          </div>
      <% end %>
    <% end %>
    </div>

	</div>
</div>