config/routes.rb
Dismassales::Application.routes.draw do
  resources :orders

  resources :categories

  resources :items

  match 'store/' => 'storefront#index', :as => :storefront
  match 'store/item/:id' => 'itemdetail#index', :as => :itemdetail
  match 'store/item/itemimage/:id' => 'itemdetail#image', :as => :itemimage
  match 'item/saveimage' => 'items#add_image', :as => :saveitemimage
  match 'store/shoppingcart' => 'shopping_cart#index', :as => :shoppingcart
  match 'store/shoppingcart/addtocart' => 'shopping_cart#addtocart', :as => :addtocart
  match 'store/shoppingcart/updatecart' => 'shopping_cart#updatecart', :as => :updatecart
  match 'store/shoppingcart/removeitem/:id' => 'shopping_cart#removeitem', :as => :removeitem
  match 'searchorders/' => 'orders#index', :as => :order_search
  match 'orderdetail/:id' => 'orders#detail', :as => :order_detail
  match 'shiporder/:id' => 'orders#shiporder', :as => :shiporder

  get "paypal_express/checkout"
  get "paypal_express/review"
  get "paypal_express/purchase"

  root :to => 'storefront#index'

end

app/models/item.rb
#implementation of the design item 2 ­ Store Home screen and 3 ­ Item Detail screen and 15 ­ Item Maintenance ­ Detail

class Item < ActiveRecord::Base
  belongs_to :category
  attr_accessible :code, :description, :enabled, :price, :show_on_home, :title, :category_id
  has_many :item_images

  def self.home_items(category_id)
  	# if there is filter for category, filter for this category, else shows the home items
  	if category_id != nil
  		items = Item.where("category_id = ?", category_id);
  	else
  		items = Item.where("show_on_home = ?", true);
  	end
  	items
  end
end

app/controllers/items_controller.rb
# implementation of the design 14 ­ Item Maintenance ­ Search and 15 ­ Item Maintenance ­ Detail

class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    @item_image = ItemImage.all.first

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])

    @item_image = ItemImage.new
    @item_image.item = @item
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  def add_image
    @item_image = ItemImage.new(params[:item_image])
    @item_image.save

    respond_to do |format|
      if @item_image.save
        format.html { redirect_to @item_image.item, notice: 'Image was successfully added.' }
        format.json { render json: @item_image.item, status: :created, location: @item_image.item }
      else
        format.html { render action: "add_image" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%-# implementation of the design 15 ­ Item Maintenance ­ Detail -%>

<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= collection_select(:item, :category_id, Category.all, :id, :title) %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :enabled %><br />
    <%= f.check_box :enabled %>
  </div>
  <div class="field">
    <%= f.label :show_on_home %><br />
    <%= f.check_box :show_on_home %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<%-# Implementation of the design item 15 ­ Item Maintenance ­ Detail %>

<h1>Editing item</h1>

<%= render 'form' %>

<%= form_for @item_image, :url => saveitemimage_path, :html => { :multipart => true } do |form| %>
  <%= hidden_field(:item_image, :item_id) %>
  <%= form.file_field :image %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Title</th>
    <th>Category</th>
    <th>Description</th>
    <th>Price</th>
    <th>Enabled</th>
    <th>Show on home</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.code %></td>
    <td><%= item.title %></td>
    <td><%= item.category.title %></td>
    <td><%= item.description %></td>
    <td><%= item.price %></td>
    <td><%= item.enabled %></td>
    <td><%= item.show_on_home %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<%-# implementation of the design 15 ­ Item Maintenance ­ Detail -%>

<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @item.code %>
</p>

<p>
  <b>Title:</b>
  <%= @item.title %>
</p>

<p>
  <b>Category:</b>
  <%= @item.category %>
</p>

<p>
  <b>Description:</b>
  <%= @item.description %>
</p>

<p>
  <b>Price:</b>
  <%= @item.price %>
</p>

<p>
  <b>Enabled:</b>
  <%= @item.enabled %>
</p>

<p>
  <b>Show on home:</b>
  <%= @item.show_on_home %>
</p>

<%= image_tag @item_image.image.url(:thumb) %>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>